use_small_heuristics = "Max"
max_width = 100
use_field_init_shorthand = true
newline_style = "Unix"
edition = "2021"
enum_discrim_align_threshold = 20
imports_granularity = "Module"
group_imports = "StdExternalCrate"
